spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


camt:
  import:
    file:
      directory: /home/marvin/Downloads

jms:
  broker-url: remote+https://host-1:8444,remote+https://host-2:8445
  context-factory: org.wildfly.naming.client.WildFlyInitialContextFactory
  connection-factory: jms/RemoteConnectionFactory
  username: jms-import
  password: password
  queue:
    costs:
      monthly: jms/queue/exampleQueue
