server:
  port: ${ADAPTER_PORT:9001}

camt:
  import:
    file:
      in: ${CAMT_DIRECTORY_IN:/app/camt}
      done: ${CAMT_DIRECTORY_DONE:/app/camt/done}
    costs:
      special:
        limit: 50

jms:
  enabled: true
  broker-url: ${JMS_URL:remote+https://192.168.178.29:8446}
  context-factory: org.wildfly.naming.client.WildFlyInitialContextFactory
  connection-factory: jms/RemoteConnectionFactory
  username: jms-import
  password: password
  queue:
    costs:
      import:
        monthly: /jms/queue/costs/import/monthly
        special: /jms/queue/costs/import/special
        salary: /jms/queue/costs/import/salary
      export:
        monthly: /jms/queue/costs/export/monthly
        special: /jms/queue/costs/export/special
        salary: /jms/queue/costs/export/salary
        daily: /jms/queue/costs/export/daily

influxdb:
  url: ${INFLUX_URL:http://192.168.178.29:8086}
  token: ${INFLUX_TOKEN:rmz5aaaKYSpgvXSO3C1UFZmXjvtpwI81b7hcMaMJJqOTjvgI82iNAbSsF7fpGIy2fduNDKACQ759cyaiECrulg==}
