server:
  port: ${ADAPTER_PORT:9001}

camt:
  import:
    file:
      directory: ${CAMT_DIRECTORY:/camt/data}
    costs:
      special:
        limit: 50

jms:
  enabled: true
  broker-url: ${JMS_URL:remote+https://192.168.178.27:8446}
  context-factory: org.wildfly.naming.client.WildFlyInitialContextFactory
  connection-factory: jms/RemoteConnectionFactory
  username: jms-import
  password: password
  queue:
    costs:
      import:
        monthly: /jms/queue/costs/import/monthly
        special: /jms/queue/costs/import/special
        salary: /jms/queue/costs/import/salary
      export:
        monthly: /jms/queue/costs/export/monthly
        special: /jms/queue/costs/export/special
        salary: /jms/queue/costs/export/salary
        daily: /jms/queue/costs/export/daily

influxdb:
  url: ${INFLUX_URL:http://192.168.178.27:8086}
  token: ${INFLUX_TOKEN:x5fqphPd3FsegObAaLRKMjEAAGncJrNgjDsTuvV_BprnRxdm7K4tcTLhjORKtLlmvCXCsR2UnIieQme81U06fg==}
